services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    restart: always
    ports:
      - "1194:1194/udp"
    volumes:
      - storage_openvpn:/etc/openvpn

volumes:
  storage_openvpn:
    name: storage_openvpn