services:

  postgresql:
    image: postgres:15.7
    container_name: confluence_db
    restart: always
    environment:
      - POSTGRES_DB=confluence
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=confluence
    expose:
      - "5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  
  confluence:
    image: atlassian/confluence:8.9.1
    container_name: confluence_app
    restart: always
    environment:
      - ATL_PROXY_NAME=wiki.example.com
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/confluence
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=confluence
      - ATL_DB_TYPE=postgresql
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - ./data/app:/var/atlassian/application-data/confluence
    depends_on:
      - postgresql