services:
  confluence_db:
    image: postgres:15.7
    container_name: confluence_db
    restart: always
    environment:
      - POSTGRES_DB=confluence
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=confluence
    expose:
      - "5432"
    volumes:
      - storage_confluence_db:/var/lib/postgresql/data
  confluence_app:
    image: atlassian/confluence:8.9.1
    container_name: confluence_app
    restart: always
    environment:
      - ATL_PROXY_NAME=wiki.example.com
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/confluence
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=confluence
      - ATL_DB_TYPE=postgresql
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - storage_confluence_app:/var/atlassian/application-data/confluence
    depends_on:
      - postgresql

volumes:
  storage_confulence_db:
    name: storage_confluence_db
  storage_confulence_app:
    name: storage_confluence_app