services:
  marzban:
    image: gozargah/marzban:v0.4.9
    restart: always
    env_file: .env
    network_mode: host
    expose:
      - "8000"
      - "8443"
      - "8080"
      - "8081"
      - "1080"
      - "2053"
      - "2083"
      - "1080"
      - "19284"
    volumes:
      - ./data/config:/var/lib/marzban
