services:

  cmdbuild_db:
    image: mdillon/postgis:9.5-alpine    
    container_name: cmdbuild_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - vlme_cmdbuild_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  cmdbuild_app:
    image: trepz/cmdbuild:3.1.1
    container_name: cmdbuild_app
    restart: always
    environment:
      - DB_HOST=cmdbuild_db
      - DB_PORT=5432
      - DB_NAME=cmdbuild
      - DB_TYPE=empty
      - CMDBUILD_USERNAME=cmdbuild
      - CMDBUILD_PASSWORD=cmdbuild
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:  
      - "8080:8080"
    depends_on:
      cmdbuild_db:
        condition: service_healthy

volumes:
  vlme_cmdbuild_db:
    name: vlme_cmdbuild_db
