services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    container_name: gitlab
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - "80:80"
      - "2224:22"
    expose:
      - "443"
    volumes:
      - storage_gitlab_config:/etc/gitlab
      - storage_gitlab_logs:/var/log/gitlab
      - storage_gitlab_data:/var/opt/gitlab
    shm_size: 256m

volumes:
  storage_gitlab_config:
    name: storage_gitlab_config
  storage_gitlab_logs:
    name: storage_gitlab_logs
  storage_gitlab_data:
    name: storage_gitlab_data