services:
  proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy_manager
    restart: always
    network_mode: host
    expose:
      - "80"
      - "81"
      - "443"
    volumes:
      - storage_proxy_manager:/data
      - storage_letsencrypt:/etc/letsencrypt

volumes:
  storage_proxy_manager:
    name: storage_proxy_manager
  storage_letsencrypt:
    name: storage_letsencrypt